---
- hosts: all
  vars:
    first_task_file: /tmp/test_11692_first_task
    second_task_file: /tmp/test_11692_second_task

  pre_tasks:
    - name: remove {{ item }}
      file: path={{ item }} state=absent
      with_items: [ first_task_file, second_task_file ]

  roles:
    - test_11692

  tasks:
    - name: exists {{ first_task_file }}
      stat: path={{ first_task_file }}
      register: stat_first_task_file

    - name: exists {{ second_task_file }}
      stat: path={{ second_task_file }}
      register: stat_second_task_file

    - name: assert {{ first_task_file }} not exists
      assert: { that: not stat_first_task_file.stat.exists }

    - name: assert {{ second_task_file }} exists
      assert: { that: stat_second_task_file.stat.exists }

  post_tasks:
#    - name: cleanup {{ item }}
#      file: path={{ item }} state=absent
#      with_items: [ first_task_file, second_task_file ]

    - name: cleanup {{ first_task_file }}
      file: path={{ first_task_file }} state=absent

    - name: cleanup {{ second_task_file }}
      file: path={{ second_task_file }} state=absent
